El siguiente código permite utilizar una red neuronal previamente entrenada para predecir posiciones.

In [ ]:
import numpy as np
from keras import models
from keras import layers
from mpl_toolkits.mplot3d import Axes3D
import matplotlib.pyplot as plt
import tensorflow as tf
import math
import random
from tensorflow.keras.models import load_model
tf.compat.v1.enable_eager_execution()
import seaborn as sns
sns.set_theme()

from google.colab import drive
drive.mount('/content/drive')

In [ ]:
model = load_model('/content/drive/MyDrive/LABO 6 y 7/Experimentos_60m/red_20_04_1200ep_random_decimalextra_r.h5') #Acá se carga el modelo entrenado.
data=np.loadtxt('/content/drive/MyDrive/RedGabo_Felipe & Constanza/Data1.txt') #acá se cargan los delays temporales

xyz= model.predict(data)

print(xyz)

[[-18.009375   -18.239756     0.46733284]
 [-17.943193   -17.515137     0.46906212]
 [-17.789541   -16.676096     0.47186822]
 ...
 [ -0.0468604   -0.19284451   0.49649313]
 [ -0.0468604   -0.19284451   0.49649313]
 [ -0.0468604   -0.19284451   0.49649313]]
